repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 2c9f875913ee60ca25ce70243dc24d5b6415598c  # frozen: v4.6.0
    hooks:
    -   id: check-added-large-files
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-json
    -   id: check-toml
    -   id: check-yaml
    -   id: check-case-conflict

-   repo: https://github.com/psf/black
    rev: 8fe627072f15ff2e3d380887b92f7868efaf6d05  # frozen: 24.4.0
    hooks:
    - id: black

-   repo: https://github.com/PyCQA/isort
    rev: c235f5e450b4b84e58d114ed4c589cbf454175a3  # frozen: 5.13.2
    hooks:
    - id: isort
